"""edited maze table

Revision ID: 3c7a826ee648
Revises: 60e52f1ec26c
Create Date: 2023-05-15 16:10:04.199279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c7a826ee648'
down_revision = '60e52f1ec26c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mazes', sa.Column('maze', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mazes', 'maze')
    # ### end Alembic commands ###
